version: '3.1'

services:
  pg_db:
    container_name: source_pg_db
    image: postgres
    restart: always
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: src_db

  my_db:
    container_name: dest_my_db
    image: mariadb
    restart: always
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MARIADB_DATABASE: dest_db

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:8080
    environment:
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_DEFAULT_EMAIL: me@me.me
      PGADMIN_DEFAULT_PASSWORD: password